swagger: "2.0"
info:
    title: Chatter service describing the streaming features of goa v2.
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /echoer:
        get:
            tags:
                - chatter
            summary: echoer chatter
            description: |-
                Echoes the message sent by the client.

                **Required security scopes for jwt**:
                  * `stream:write`
            operationId: chatter#echoer
            parameters:
                - name: Authorization
                  in: header
                  description: JWT used for authentication
                  required: true
                  type: string
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        type: string
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
                "403":
                    description: Forbidden response.
                    schema:
                        type: string
            schemes:
                - ws
            security:
                - jwt_header_Authorization: []
    /history:
        get:
            tags:
                - chatter
            summary: history chatter
            description: |-
                Returns the chat messages sent to the server.

                **Required security scopes for jwt**:
                  * `stream:read`
            operationId: chatter#history
            parameters:
                - name: view
                  in: query
                  description: View to use to render the result
                  required: false
                  type: string
                - name: Authorization
                  in: header
                  description: JWT used for authentication
                  required: true
                  type: string
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/ChatterHistoryResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
                "403":
                    description: Forbidden response.
                    schema:
                        type: string
            schemes:
                - ws
            security:
                - jwt_header_Authorization: []
    /listener:
        get:
            tags:
                - chatter
            summary: listener chatter
            description: |-
                Listens to the messages sent by the client.

                **Required security scopes for jwt**:
                  * `stream:write`
            operationId: chatter#listener
            parameters:
                - name: Authorization
                  in: header
                  description: JWT used for authentication
                  required: true
                  type: string
            responses:
                "101":
                    description: Switching Protocols response.
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
                "403":
                    description: Forbidden response.
                    schema:
                        type: string
            schemes:
                - ws
            security:
                - jwt_header_Authorization: []
    /login:
        post:
            tags:
                - chatter
            summary: login chatter
            description: Creates a valid JWT token for auth to chat.
            operationId: chatter#login
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - basic_header_Authorization: []
    /subscribe:
        get:
            tags:
                - chatter
            summary: subscribe chatter
            description: |-
                Subscribe to events sent when new chat messages are added.

                **Required security scopes for jwt**:
                  * `stream:write`
            operationId: chatter#subscribe
            parameters:
                - name: Authorization
                  in: header
                  description: JWT used for authentication
                  required: true
                  type: string
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/ChatterSubscribeResponseBody'
                        required:
                            - message
                            - action
                            - added_at
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
                "403":
                    description: Forbidden response.
                    schema:
                        type: string
            schemes:
                - ws
            security:
                - jwt_header_Authorization: []
    /summary:
        get:
            tags:
                - chatter
            summary: summary chatter
            description: |-
                Summarizes the chat messages sent by the client.

                **Required security scopes for jwt**:
                  * `stream:write`
            operationId: chatter#summary
            parameters:
                - name: Authorization
                  in: header
                  description: JWT used for authentication
                  required: true
                  type: string
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/ChatterChatSummaryResponseCollection'
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
                "403":
                    description: Forbidden response.
                    schema:
                        type: string
            schemes:
                - ws
            security:
                - jwt_header_Authorization: []
definitions:
    ChatSummaryResponse:
        title: 'Mediatype identifier: application/vnd.goa.summary; view=default'
        type: object
        properties:
            length:
                type: integer
                description: Length of the message sent
                example: 8984490481125427857
                format: int64
            message:
                type: string
                description: Message sent to the server
                example: Molestias et aut.
            sent_at:
                type: string
                description: Time at which the message was sent
                example: "2013-09-10T22:57:42Z"
                format: date-time
        description: ChatSummaryResponse result type (default view)
        example:
            length: 5929104825104027564
            message: Voluptas laboriosam omnis.
            sent_at: "1979-10-06T12:25:24Z"
        required:
            - message
            - sent_at
    ChatterChatSummaryResponseCollection:
        title: 'Mediatype identifier: application/vnd.goa.summary; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/ChatSummaryResponse'
        description: SummaryResponseBody is the result type for an array of ChatSummaryResponse (default view)
        example:
            - length: 7192545811968992741
              message: In quo soluta ducimus blanditiis.
              sent_at: "2000-11-29T18:15:59Z"
            - length: 7192545811968992741
              message: In quo soluta ducimus blanditiis.
              sent_at: "2000-11-29T18:15:59Z"
            - length: 7192545811968992741
              message: In quo soluta ducimus blanditiis.
              sent_at: "2000-11-29T18:15:59Z"
            - length: 7192545811968992741
              message: In quo soluta ducimus blanditiis.
              sent_at: "2000-11-29T18:15:59Z"
    ChatterHistoryResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.summary; view=default'
        type: object
        properties:
            length:
                type: integer
                description: Length of the message sent
                example: 7492461781052587739
                format: int64
            message:
                type: string
                description: Message sent to the server
                example: Error eveniet dolores sapiente nostrum amet voluptatem.
            sent_at:
                type: string
                description: Time at which the message was sent
                example: "2000-04-16T19:19:54Z"
                format: date-time
        description: HistoryResponseBody result type (default view)
        example:
            length: 6204503829336269061
            message: Illum illum in molestiae labore ut.
            sent_at: "1991-04-29T19:46:35Z"
        required:
            - message
            - sent_at
    ChatterSubscribeResponseBody:
        title: ChatterSubscribeResponseBody
        type: object
        properties:
            action:
                type: string
                example: added
                enum:
                    - added
            added_at:
                type: string
                description: Time at which the message was added
                example: "1995-02-21T13:02:15Z"
                format: date-time
            message:
                type: string
                description: Message sent to the server
                example: Maiores sunt dolor quam.
        example:
            action: added
            added_at: "1980-10-26T13:18:08Z"
            message: Libero dolore.
        required:
            - message
            - action
            - added_at
securityDefinitions:
    basic_header_Authorization:
        type: basic
        description: Secures the login endpoint.
    jwt_header_Authorization:
        type: apiKey
        description: |-
            Secures endpoint by requiring a valid JWT token. Supports scopes "stream:read" and "stream:write".

            **Security Scopes**:
              * `stream:read`: Read-only access
              * `stream:write`: Read and write access
        name: Authorization
        in: header
