openapi: 3.0.3
info:
    title: Chatter service describing the streaming features of goa v2.
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for chatter
paths:
    /echoer:
        get:
            tags:
                - chatter
            summary: echoer chatter
            description: Echoes the message sent by the client.
            operationId: chatter#echoer
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Qui veritatis ea suscipit.
                            example: Aspernatur nulla deleniti.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Voluptas quia eligendi et eaque.
                            example: Sunt sit voluptatibus.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Molestiae iure assumenda.
                            example: Atque et magnam blanditiis voluptates.
            security:
                - jwt_header_Authorization:
                    - stream:write
    /history:
        get:
            tags:
                - chatter
            summary: history chatter
            description: Returns the chat messages sent to the server.
            operationId: chatter#history
            parameters:
                - name: view
                  in: query
                  description: View to use to render the result
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to use to render the result
                    example: Nihil sed.
                  example: Impedit ut odio vel saepe illum iusto.
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GoaSummary'
                            example:
                                length: 7051438596234715468
                                message: Consequatur facilis perferendis ad quos.
                                sent_at: "1997-03-12T03:19:42Z"
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quaerat asperiores fugit ducimus dolorem.
                            example: Inventore ut ut id eveniet eum eveniet.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Voluptates tempore non amet sunt aut deserunt.
                            example: In in ut sint incidunt enim.
            security:
                - jwt_header_Authorization:
                    - stream:read
    /listener:
        get:
            tags:
                - chatter
            summary: listener chatter
            description: Listens to the messages sent by the client.
            operationId: chatter#listener
            responses:
                "101":
                    description: Switching Protocols response.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Doloremque quo neque rerum.
                            example: Soluta ipsam cupiditate.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Reprehenderit autem necessitatibus esse unde adipisci.
                            example: Et sed.
            security:
                - jwt_header_Authorization:
                    - stream:write
    /login:
        post:
            tags:
                - chatter
            summary: login chatter
            description: Creates a valid JWT token for auth to chat.
            operationId: chatter#login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: New JWT token
                                example: Laborum ducimus velit ipsam sequi.
                            example: Repudiandae sunt molestias qui doloribus.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Provident dolorum est voluptatibus enim aliquid.
                            example: Et et amet.
            security:
                - basic_header_Authorization: []
    /subscribe:
        get:
            tags:
                - chatter
            summary: subscribe chatter
            description: Subscribe to events sent when new chat messages are added.
            operationId: chatter#subscribe
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Event'
                            example:
                                action: added
                                added_at: "1995-12-26T18:55:28Z"
                                message: Laudantium est consectetur ut.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Id error nulla.
                            example: Eum adipisci iusto occaecati rerum earum.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Beatae dicta.
                            example: Sint consequatur sit cupiditate neque vel sint.
            security:
                - jwt_header_Authorization:
                    - stream:write
    /summary:
        get:
            tags:
                - chatter
            summary: summary chatter
            description: Summarizes the chat messages sent by the client.
            operationId: chatter#summary
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatSummaryResponseCollection'
                            example:
                                - length: 7192545811968992741
                                  message: In quo soluta ducimus blanditiis.
                                  sent_at: "2000-11-29T18:15:59Z"
                                - length: 7192545811968992741
                                  message: In quo soluta ducimus blanditiis.
                                  sent_at: "2000-11-29T18:15:59Z"
                                - length: 7192545811968992741
                                  message: In quo soluta ducimus blanditiis.
                                  sent_at: "2000-11-29T18:15:59Z"
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Inventore dolores.
                            example: A ut ut aut voluptates sit.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Iusto neque minus sit quae incidunt.
                            example: Quisquam deserunt suscipit quia.
            security:
                - jwt_header_Authorization:
                    - stream:write
components:
    schemas:
        ChatSummaryResponse:
            type: object
            properties:
                length:
                    type: integer
                    description: Length of the message sent
                    example: 8660456896459588679
                    format: int64
                message:
                    type: string
                    description: Message sent to the server
                    example: Itaque tempore earum quae fugiat enim.
                sent_at:
                    type: string
                    description: Time at which the message was sent
                    example: "2016-01-14T18:54:25Z"
                    format: date-time
            description: ChatSummaryResponse result type (default view)
            example:
                length: 8740123299469121795
                message: Iusto quis quibusdam voluptatum nemo.
                sent_at: "1974-11-23T04:59:48Z"
            required:
                - message
                - sent_at
        ChatSummaryResponseCollection:
            type: array
            items:
                $ref: '#/components/schemas/ChatSummaryResponse'
            description: SummaryResponseBody is the result type for an array of ChatSummaryResponse (default view)
            example:
                - length: 7192545811968992741
                  message: In quo soluta ducimus blanditiis.
                  sent_at: "2000-11-29T18:15:59Z"
                - length: 7192545811968992741
                  message: In quo soluta ducimus blanditiis.
                  sent_at: "2000-11-29T18:15:59Z"
        Event:
            type: object
            properties:
                action:
                    type: string
                    example: added
                    enum:
                        - added
                added_at:
                    type: string
                    description: Time at which the message was added
                    example: "2012-03-30T14:32:29Z"
                    format: date-time
                message:
                    type: string
                    description: Message sent to the server
                    example: Corporis dolorem.
            example:
                action: added
                added_at: "1984-08-20T15:36:58Z"
                message: Et fuga architecto deserunt expedita porro.
            required:
                - message
                - action
                - added_at
        GoaSummary:
            type: object
            properties:
                length:
                    type: integer
                    description: Length of the message sent
                    example: 2861419859645713776
                    format: int64
                message:
                    type: string
                    description: Message sent to the server
                    example: Omnis molestiae atque a.
                sent_at:
                    type: string
                    description: Time at which the message was sent
                    example: "2003-04-11T08:29:04Z"
                    format: date-time
            example:
                length: 4296683829615391764
                message: Dolore libero pariatur est.
                sent_at: "2014-08-22T15:57:57Z"
            required:
                - message
                - sent_at
    securitySchemes:
        basic_header_Authorization:
            type: http
            description: Secures the login endpoint.
            scheme: basic
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token. Supports scopes "stream:read" and "stream:write".
            scheme: bearer
tags:
    - name: chatter
      description: The chatter service implements a simple client and server chat.
