openapi: 3.0.3
info:
    title: Encodings Service
    description: Encoding example service demonstrating the use of different content types
    version: 0.0.1
servers:
    - url: http://localhost:80
paths:
    /concatbytes/{a}/{b}:
        get:
            tags:
                - text
            summary: concatbytes text
            operationId: text#concatbytes
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Et velit aut fugit possimus.
                  example: Et culpa quis aut.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Fugit nam incidunt vitae doloremque unde.
                  example: Ullam quos eum modi culpa vel.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example:
                                    - 69
                                    - 116
                                    - 32
                                    - 97
                                    - 117
                                    - 116
                                    - 32
                                    - 110
                                    - 101
                                    - 99
                                    - 101
                                    - 115
                                    - 115
                                    - 105
                                    - 116
                                    - 97
                                    - 116
                                    - 105
                                    - 98
                                    - 117
                                    - 115
                                    - 32
                                    - 97
                                    - 100
                                    - 46
                                format: binary
                            example:
                                - 83
                                - 97
                                - 101
                                - 112
                                - 101
                                - 32
                                - 105
                                - 110
                                - 118
                                - 101
                                - 110
                                - 116
                                - 111
                                - 114
                                - 101
                                - 32
                                - 101
                                - 116
                                - 46
    /concatbytesfield/{a}/{b}:
        get:
            tags:
                - text
            summary: concatbytesfield text
            operationId: text#concatbytesfield
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Ut sed perspiciatis ducimus voluptas similique.
                  example: Iusto a fugiat vitae sequi ut impedit.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Architecto dignissimos fuga non.
                  example: Rerum deserunt cupiditate in architecto.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example:
                                    - 69
                                    - 117
                                    - 109
                                    - 32
                                    - 118
                                    - 101
                                    - 114
                                    - 105
                                    - 116
                                    - 97
                                    - 116
                                    - 105
                                    - 115
                                    - 32
                                    - 104
                                    - 97
                                    - 114
                                    - 117
                                    - 109
                                    - 46
                                format: binary
                            example:
                                - 82
                                - 101
                                - 109
                                - 32
                                - 115
                                - 101
                                - 100
                                - 32
                                - 97
                                - 116
                                - 113
                                - 117
                                - 101
                                - 32
                                - 117
                                - 116
                                - 32
                                - 101
                                - 118
                                - 101
                                - 110
                                - 105
                                - 101
                                - 116
                                - 32
                                - 118
                                - 111
                                - 108
                                - 117
                                - 112
                                - 116
                                - 97
                                - 115
                                - 32
                                - 118
                                - 111
                                - 108
                                - 117
                                - 112
                                - 116
                                - 97
                                - 116
                                - 101
                                - 46
    /concatstringfield/{a}/{b}:
        get:
            tags:
                - text
            summary: concatstringfield text
            operationId: text#concatstringfield
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Non aut sapiente nemo hic.
                  example: Voluptas aut ipsam.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Pariatur sit vero accusamus corrupti neque.
                  example: Ab nisi autem.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example: Nihil a molestiae vitae.
                            example: Odit et ut repellendus.
    /concatstrings/{a}/{b}:
        get:
            tags:
                - text
            summary: concatstrings text
            operationId: text#concatstrings
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Asperiores rerum laudantium.
                  example: Commodi architecto voluptas nobis.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Temporibus itaque facilis animi laudantium fugiat.
                  example: Ut esse aliquam sunt sed dolor quam.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example: Alias corporis.
                            example: Velit aliquid magni.
    /swagger.json:
        get:
            tags:
                - text
            summary: Download ../../gen/http/openapi.json
            operationId: text#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        MyConcatenation:
            type: object
            properties:
                bytesfield:
                    type: string
                    example:
                        - 79
                        - 100
                        - 105
                        - 111
                        - 32
                        - 98
                        - 101
                        - 97
                        - 116
                        - 97
                        - 101
                        - 32
                        - 102
                        - 97
                        - 99
                        - 101
                        - 114
                        - 101
                        - 32
                        - 113
                        - 117
                        - 105
                        - 115
                        - 113
                        - 117
                        - 97
                        - 109
                        - 32
                        - 118
                        - 111
                        - 108
                        - 117
                        - 112
                        - 116
                        - 97
                        - 116
                        - 101
                        - 115
                        - 46
                    format: binary
                stringfield:
                    type: string
                    example: Tempora quia quia omnis quia reiciendis nostrum.
            example:
                bytesfield:
                    - 70
                    - 117
                    - 103
                    - 105
                    - 116
                    - 32
                    - 115
                    - 105
                    - 109
                    - 105
                    - 108
                    - 105
                    - 113
                    - 117
                    - 101
                    - 32
                    - 99
                    - 111
                    - 110
                    - 115
                    - 101
                    - 113
                    - 117
                    - 97
                    - 116
                    - 117
                    - 114
                    - 32
                    - 101
                    - 116
                    - 32
                    - 109
                    - 111
                    - 108
                    - 101
                    - 115
                    - 116
                    - 105
                    - 97
                    - 115
                    - 32
                    - 98
                    - 101
                    - 97
                    - 116
                    - 97
                    - 101
                    - 46
                stringfield: Aut molestias magni iusto ad aut.
tags:
    - name: text
      description: The text service performs operations on strings
